import { chapter01Lessons } from "./chapter-01.ts";
import { chapter02Lessons } from "./chapter-02.ts";
import { chapter03Lessons } from "./chapter-03.ts";
import { chapter04Lessons } from "./chapter-04.ts";
import { chapter05Lessons } from "./chapter-05.ts";
import { chapter06Lessons } from "./chapter-06.ts";
import { chapter07Lessons } from "./chapter-07.ts";
import { chapter08Lessons } from "./chapter-08.ts";
import { chapter09Lessons } from "./chapter-09.ts";
import { chapter10Lessons } from "./chapter-10.ts";
import { chapter11Lessons } from "./chapter-11.ts";
import { chapter12Lessons } from "./chapter-12.ts";
import { chapter13Lessons } from "./chapter-13.ts";
import { chapter14Lessons } from "./chapter-14.ts";
import { chapter15Lessons } from "./chapter-15.ts";
import { chapter16Lessons } from "./chapter-16.ts";
import { chapter17Lessons } from "./chapter-17.ts";
import { chapter18Lessons } from "./chapter-18.ts";
import { chapter19Lessons } from "./chapter-19.ts";
import { chapter20Lessons } from "./chapter-20.ts";
import { chapter21Lessons } from "./chapter-21.ts";
import { chapter22Lessons } from "./chapter-22.ts";
import { chapter23Lessons } from "./chapter-23.ts";
import { chapter24Lessons } from "./chapter-24.ts";
export type * from "./types.ts";
export const lessons = [...chapter01Lessons,...chapter02Lessons,...chapter03Lessons,...chapter04Lessons,...chapter05Lessons,...chapter06Lessons,...chapter07Lessons,...chapter08Lessons,...chapter09Lessons,...chapter10Lessons,...chapter11Lessons,...chapter12Lessons,...chapter13Lessons,...chapter14Lessons,...chapter15Lessons,...chapter16Lessons,...chapter17Lessons,...chapter18Lessons,...chapter19Lessons,...chapter20Lessons,...chapter21Lessons,...chapter22Lessons,...chapter23Lessons,...chapter24Lessons];
